/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlmanaccoRouteImport } from './routes/almanacco'
import { Route as AltroRouteImport } from './routes/altro'
import { Route as AnnunciRouteImport } from './routes/annunci'
import { Route as CampionatoRouteImport } from './routes/campionato'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LotteriaRouteImport } from './routes/lotteria'
import { Route as PostoRouteImport } from './routes/posto'
import { Route as RedazioneRouteImport } from './routes/redazione'
import { Route as SfideIndexRouteImport } from './routes/sfide/index'
import { Route as SfideIdRouteImport } from './routes/sfide/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmanaccoRoute = AlmanaccoRouteImport.update({
  id: '/almanacco',
  path: '/almanacco',
  getParentRoute: () => rootRouteImport,
} as any)
const AltroRoute = AltroRouteImport.update({
  id: '/altro',
  path: '/altro',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnunciRoute = AnnunciRouteImport.update({
  id: '/annunci',
  path: '/annunci',
  getParentRoute: () => rootRouteImport,
} as any)
const CampionatoRoute = CampionatoRouteImport.update({
  id: '/campionato',
  path: '/campionato',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LotteriaRoute = LotteriaRouteImport.update({
  id: '/lotteria',
  path: '/lotteria',
  getParentRoute: () => rootRouteImport,
} as any)
const PostoRoute = PostoRouteImport.update({
  id: '/posto',
  path: '/posto',
  getParentRoute: () => rootRouteImport,
} as any)
const RedazioneRoute = RedazioneRouteImport.update({
  id: '/redazione',
  path: '/redazione',
  getParentRoute: () => rootRouteImport,
} as any)
const SfideIndexRoute = SfideIndexRouteImport.update({
  id: '/sfide/',
  path: '/sfide/',
  getParentRoute: () => rootRouteImport,
} as any)
const SfideIdRoute = SfideIdRouteImport.update({
  id: '/sfide/$id',
  path: '/sfide/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/almanacco': typeof AlmanaccoRoute
  '/altro': typeof AltroRoute
  '/annunci': typeof AnnunciRoute
  '/campionato': typeof CampionatoRoute
  '/login': typeof LoginRoute
  '/lotteria': typeof LotteriaRoute
  '/posto': typeof PostoRoute
  '/redazione': typeof RedazioneRoute
  '/sfide/$id': typeof SfideIdRoute
  '/sfide/': typeof SfideIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/almanacco': typeof AlmanaccoRoute
  '/altro': typeof AltroRoute
  '/annunci': typeof AnnunciRoute
  '/campionato': typeof CampionatoRoute
  '/login': typeof LoginRoute
  '/lotteria': typeof LotteriaRoute
  '/posto': typeof PostoRoute
  '/redazione': typeof RedazioneRoute
  '/sfide/$id': typeof SfideIdRoute
  '/sfide': typeof SfideIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/almanacco': typeof AlmanaccoRoute
  '/altro': typeof AltroRoute
  '/annunci': typeof AnnunciRoute
  '/campionato': typeof CampionatoRoute
  '/login': typeof LoginRoute
  '/lotteria': typeof LotteriaRoute
  '/posto': typeof PostoRoute
  '/redazione': typeof RedazioneRoute
  '/sfide/$id': typeof SfideIdRoute
  '/sfide/': typeof SfideIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/almanacco'
    | '/altro'
    | '/annunci'
    | '/campionato'
    | '/login'
    | '/lotteria'
    | '/posto'
    | '/redazione'
    | '/sfide/$id'
    | '/sfide/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/almanacco'
    | '/altro'
    | '/annunci'
    | '/campionato'
    | '/login'
    | '/lotteria'
    | '/posto'
    | '/redazione'
    | '/sfide/$id'
    | '/sfide'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/almanacco'
    | '/altro'
    | '/annunci'
    | '/campionato'
    | '/login'
    | '/lotteria'
    | '/posto'
    | '/redazione'
    | '/sfide/$id'
    | '/sfide/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlmanaccoRoute: typeof AlmanaccoRoute
  AltroRoute: typeof AltroRoute
  AnnunciRoute: typeof AnnunciRoute
  CampionatoRoute: typeof CampionatoRoute
  LoginRoute: typeof LoginRoute
  LotteriaRoute: typeof LotteriaRoute
  PostoRoute: typeof PostoRoute
  RedazioneRoute: typeof RedazioneRoute
  SfideIdRoute: typeof SfideIdRoute
  SfideIndexRoute: typeof SfideIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanacco': {
      id: '/almanacco'
      path: '/almanacco'
      fullPath: '/almanacco'
      preLoaderRoute: typeof AlmanaccoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/altro': {
      id: '/altro'
      path: '/altro'
      fullPath: '/altro'
      preLoaderRoute: typeof AltroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annunci': {
      id: '/annunci'
      path: '/annunci'
      fullPath: '/annunci'
      preLoaderRoute: typeof AnnunciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campionato': {
      id: '/campionato'
      path: '/campionato'
      fullPath: '/campionato'
      preLoaderRoute: typeof CampionatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotteria': {
      id: '/lotteria'
      path: '/lotteria'
      fullPath: '/lotteria'
      preLoaderRoute: typeof LotteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posto': {
      id: '/posto'
      path: '/posto'
      fullPath: '/posto'
      preLoaderRoute: typeof PostoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redazione': {
      id: '/redazione'
      path: '/redazione'
      fullPath: '/redazione'
      preLoaderRoute: typeof RedazioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sfide/': {
      id: '/sfide/'
      path: '/sfide'
      fullPath: '/sfide/'
      preLoaderRoute: typeof SfideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sfide/$id': {
      id: '/sfide/$id'
      path: '/sfide/$id'
      fullPath: '/sfide/$id'
      preLoaderRoute: typeof SfideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlmanaccoRoute: AlmanaccoRoute,
  AltroRoute: AltroRoute,
  AnnunciRoute: AnnunciRoute,
  CampionatoRoute: CampionatoRoute,
  LoginRoute: LoginRoute,
  LotteriaRoute: LotteriaRoute,
  PostoRoute: PostoRoute,
  RedazioneRoute: RedazioneRoute,
  SfideIdRoute: SfideIdRoute,
  SfideIndexRoute: SfideIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
